package rpcs3_patch

import (
	"debug/elf"

	"git.valtek.uk/HugeSpaceship/patchwork/tools/patch_generator"
)

func CUtf8Patch(address uint32, value string) PatchEntry {
	return PatchEntry{
		Type:    CUtf8PatchType,
		Value:   value,
		Address: address,
	}
}

func MakePatches(elfFile *elf.File, game patch_generator.Game, servers []patch_generator.Server) PatchMap {

	patches := make(PatchMap)

	syms, err := elfFile.Symbols()
	if err != nil {
		panic(err)
	}

	var patchEntries []PatchEntry
	for _, sym := range syms {
		if sym.Name == game.SymbolName {
			gameHook, err := patch_generator.GetHook(elfFile.Section(".text"), sym.Value)
			if err != nil {
				panic(err)
			}
			patchEntries = MakeCodePatch(game.Offsets.ResourceCheck, gameHook)
		}
	}

	patchEntries = append(patchEntries, CUtf8Patch(game.Offsets.UserAgent, game.UserAgent))

	titleIDVersionMap := make(map[string][]string)
	for _, d := range game.TitleIDs {
		titleIDVersionMap[d] = game.GameVersions
	}

	gamePatch := RPCS3Patch{
		Games: map[string]map[string][]string{
			game.Name: titleIDVersionMap,
		},
		Author:       "HugeSpaceship contributors",
		Notes:        "Combined patch from patchwork sources",
		PatchVersion: 1.0,
		Patch:        patchEntries,
	}
	patches[game.PPUHash] = make(map[string]RPCS3Patch)
	patches[game.PPUHash]["Patchwork Combined Patch"] = gamePatch

	// Add servers to patch
	for _, server := range servers {
		var serverPatches []PatchEntry
		serverPatches = append(serverPatches, CUtf8Patch(game.Offsets.HttpURL, server.PrimaryURL))

		HttpsURL := server.HttpsURL
		if HttpsURL == "" {
			HttpsURL = server.PrimaryURL
		}
		serverPatches = append(serverPatches, CUtf8Patch(game.Offsets.HttpsURL, HttpsURL))

		if game.Offsets.LiveURL != 0 {
			serverPatches = append(serverPatches, CUtf8Patch(game.Offsets.LiveURL, server.PrimaryURL))
		}
		if game.Offsets.PresenceURL != 0 {
			serverPatches = append(serverPatches, CUtf8Patch(game.Offsets.PresenceURL, server.PrimaryURL))
		}
		if server.CustomDigest != "" {
			serverPatches = append(serverPatches, CUtf8Patch(game.Offsets.DigestKey, server.CustomDigest))
		}

		patches[game.PPUHash][server.Name+" Custom Server"] = RPCS3Patch{
			Games: map[string]map[string][]string{
				game.Name: titleIDVersionMap,
			},
			Author:       server.Owner + " (Autogenerated by Patchwork)",
			Notes:        server.Description + "\n" + "(Autogenerated by patchwork)",
			PatchVersion: 1.0,
			Patch:        serverPatches,
		}
	}
	return patches
}
