---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: patchwork-build
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/on-event: "push"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/on-path-change: "[Makefile, config.mk, src/***, .tekton/patchwork-build.yaml, patch-generator/***, lbpdefs/*, go.mod, go.sum]"
spec:
  params:
    - name: repo_url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    tasks:
      - name: fetch
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: fetch-repo
              ref:
                resolver: hub
                params:
                  - name: catalog
                    value: git-clone-stepaction
                  - name: type
                    value: artifact
                  - name: kind
                    value: stepaction
                  - name: name
                    value: git-clone
                  - name: version
                    value: "1.7.0"
              params:
                - name: output-path
                  value: $(workspaces.source.path)
                - name: url
                  value: "$(params.repo_url)"
                - name: revision
                  value: "$(params.revision)"
      - name: build
        runAfter:
          - fetch
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: build
              image: git.valtek.uk/hugespaceship/ps3sdk-475-win:latest
              env:
                - name: COMMIT_SHA
                  value: "{{revision}}"
                - name: BUILD_ID
                  value: "$(context.pipelineRun.name)"
              workingDir: $(workspaces.source.path)
              script: |
                #!/usr/bin/env bash
                set -euo pipefail
                ln -s /usr/local/cell/real/Tools/data .
                make
      - name: go-build
        runAfter:
          - fetch
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: build
              image: docker.io/library/golang:latest
              workingDir: "$(workspaces.source.path)"
              script: |
                #!/usr/bin/env bash
                set -euo pipefail
                git config --global --add safe.directory $(workspaces.source.path)
                GIT_TRACE_CURL=1 GIT_TRACE=1 go get -v ./patch-generator
                go build -o patchgen ./patch-generator
      - name: patch-generate
        runAfter:
          - go-build
          - build
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: generate-patches
              image: docker.io/library/alpine:latest
              workingDir: "$(workspaces.source.path)"
              script: |
                #!/usr/bin/env sh
                ./patchgen -input ./patchwork.prx -config ./lbpdefs -output ./patchwork-rpcs3-patch.yml
      - name: upload-artifacts
        runAfter:
          - patch-generate
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: source
            - name: forgejo-token
          steps:
            - name: upload
              image: curlimages/curl:latest
              workingDir: "$(workspaces.source.path)"
              env:
                - name: BUILD_ID
                  value: "$(context.pipelineRun.name)"
                - name: COMMIT_SHA
                  value: "{{revision}}"
              script: |
                #!/usr/bin/env sh
                curl -X PUT --upload-file ./patchwork-fake-signed.sprx --user tekton:`cat $(workspaces.forgejo-token.path)/provider.token` https://git.valtek.uk/api/packages/hugespaceship/generic/patchwork/`make -q print-version`-$COMMIT_SHA/patchwork-fake-signed.sprx
                curl -X PUT --upload-file ./patchwork-signed.sprx --user tekton:`cat $(workspaces.forgejo-token.path)/provider.token` https://git.valtek.uk/api/packages/hugespaceship/generic/patchwork/`make -q print-version`-$COMMIT_SHA/patchwork-signed.sprx
                curl -X PUT --upload-file ./patchwork.prx --user tekton:`cat $(workspaces.forgejo-token.path)/provider.token` https://git.valtek.uk/api/packages/hugespaceship/generic/patchwork/`make -q print-version`-$COMMIT_SHA/patchwork.prx
                curl -X PUT --upload-file ./patchwork-rpcs3-patch.yml --user tekton:`cat $(workspaces.forgejo-token.path)/provider.token` https://git.valtek.uk/api/packages/hugespaceship/generic/patchwork/`make -q print-version`-$COMMIT_SHA/patchwork-rpcs3-patch.yml
      - name: cleanup
        runAfter:
          - upload-artifacts
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          steps:
            - name: cleanup
              image: docker.io/library/alpine:latest
              workingDir: "$(workspaces.source.path)"
              script: |
                #!/usr/bin/env sh
                rm -rf ./*
    workspaces:
      - name: source
  workspaces:
    - name: gocache
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
    - name: forgejo-token
      secret:
        secretName: forgejo-webhook-config