name: release.yml
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set PS3_SDK path
        id: set_ps3_sdk
        run: |
          $workspacePath = "${{ github.workspace }}" -replace '\\', '/'
          echo "PS3_SDK=$workspacePath/PS3_SDK/cell" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh


      - name: Check if PS3 SDK is already downloaded
        id: check_ps3_sdk
        run: |
          if [[ -d "${{ env.PS3_SDK }}" ]]; then
            echo "::set-output name=sdk_exists::true"
          else
            echo "::set-output name=sdk_exists::false"
          fi
        shell: bash


      - name: Download and extract PS3 SDK
        if: steps.check_ps3_sdk.outputs.sdk_exists == 'false'
        run: |
          Invoke-WebRequest -Uri https://bordplate.no/cell.zip -OutFile PS3_SDK.zip
          Expand-Archive -Path PS3_SDK.zip -DestinationPath "${{ env.PS3_SDK }}/../"
        shell: pwsh

      - name: Install Dependencies
        run: |
          choco install make
        shell: pwsh
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0-${{ github.run_number }}+${{ github.run_id }}
          release_name: Release v1.0-${{ github.run_number }}+${{ github.run_id }}
          draft: false

      - name: Upload sprx
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./patchwork.sprx
          asset_name: patchwork.sprx
          asset_content_type: application/octet-stream
      - name: Upload prx
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./patchwork.prx
          asset_name: patchwork.prx
          asset_content_type: application/octet-stream