name: release.yml
on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set PS3_SDK path
        id: set_ps3_sdk
        run: |
          $workspacePath = "${{ github.workspace }}" -replace '\\', '/'
          echo "CELL_SDK=$workspacePath/PS3_SDK/cell" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "SCETOOL=$workspacePath/PS3_SDK/cell/Tools/scetool.2.9.exe" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "PS3=$workspacePath/PS3_SDK/cell/Tools/data" | Out-File -FilePath $env:GITHUB_ENV -Append

        shell: pwsh


      - name: Check if PS3 SDK is already downloaded
        id: check_ps3_sdk
        run: |
          if [[ -d "${{ env.CELL_SDK }}" ]]; then
            echo "sdk_exists=true" >> $GITHUB_OUTPUT
          else
            echo "sdk_exists=false" >> $GITHUB_OUTPUT
          fi
        shell: bash


      - name: Download and extract PS3 SDK
        if: steps.check_ps3_sdk.outputs.sdk_exists == 'false'
        run: |
          Invoke-WebRequest -Uri https://bordplate.no/cell.zip -OutFile PS3_SDK.zip
          Expand-Archive -Path PS3_SDK.zip -DestinationPath "${{ env.CELL_SDK }}/../"
        shell: pwsh

      - name: Install Dependencies
        run: |
          choco install make
        shell: pwsh

      - name: Build prx
        run: |
          make
        shell: pwsh

      - uses: dev-drprasad/delete-tag-and-release@v1.1
        if: github.ref_type != 'tag'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: latest
          delete_release: true

      # Apparently this is why everything is drafts
      - name: Wait a sec
        run: sleep 2

      - name: Latest Prerelease
        uses: softprops/action-gh-release@v2
        if: github.ref_type != 'tag'
        with:
          prerelease: true
          name: "Latest Snapshot"
          body: "The absolute latest version, straight from the main branch, may contain bugs"
          generate_release_notes: true
          tag_name: latest
          files: |
            ./patchwork.sprx
            ./patchwork.prx

      - name: Tagged Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          make_latest: true
          files: |
            ./patchwork.sprx
            ./patchwork.prx